# Generated by Django 4.1 on 2026-01-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='location',
            field=models.CharField(default='unkown', max_length=50),
            preserve_default=False,
        ),
    ]
